app:
  security:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always
      roles: ADMIN

logging:
  level:
    root: INFO
    com.cargo.booking: DEBUG
